const generateCssFile = require('./generateCssFile');
const fs = require("fs");
const path = require("path");

// build css file content
generateCssFile()
    .then(css => new Promise((resolve, reject) => {
        // add header to content
        css = "// THIS IS AN AUTOGENERATED FILE, BUILD USING ./tools/buildCss.js\n\n" + css;

        // write file
        fs.writeFile(
            path.resolve(__dirname, "../src/css.ts"),
            css,
            err => err ? reject(err) : resolve());
    }))
    .then(() => console.log("Css file Complete"))
    .catch(err => console.error(err));